import DefAIkeDomain
import Foundation
import PropertyBased
import Testing

@testable import DefAIkeSharedTransfer

// Design Property 5: handoff session and encoded-byte preservation.
//
// The design states it as: for any finite encoded byte sequence, any chunk partition, any
// valid Byte Preservation Status, and either supported route, retaining and routing the
// asset to validation and enabled provenance preserves the exact byte sequence, byte count,
// SHA-256 digest, and unchanged status; for any confirmed Share handoff whose atomic ready
// publication succeeds, that commit creates exactly one pending `AnalysisSessionID`, and
// claim resumes that same identifier.
//
// Five things must stay exact end to end, and this file quantifies each of them over
// generated byte sequences, generated chunk partitions, generated preservation bases, and
// both routes:
//
//   * **the bytes** — every object read back equals the generated array element for element,
//     never merely "the digests agree" (Requirements 2.9 through 2.11);
//   * **the byte count** — the count the store measured while writing, the count the ticket
//     published, and the count the resumed session carries are one number;
//   * **the digest** — the same three places agree, and on the claiming side the digest is
//     shown to have been *measured from bytes this process streamed* rather than copied from
//     the ticket it is being compared against (Requirements 2.19 and 11.13);
//   * **the status** — derived from the basis rather than chosen, and carried across the App
//     Group boundary unchanged (Requirements 2.9 through 2.11 and 11.12);
//   * **the session identifier** — the candidate the extension allocated is the identifier
//     the publication commit turns into exactly one pending session, and it is the identifier
//     claim resumes (Requirements 2.3 and 11.12).
//
// ## Why the chunk partition is generated
//
// A partition must not change any outcome — that is the point of generating one. Three
// partitions of the same sequence are written per case: the whole sequence in one append, a
// generated non-uniform partition, and the uniform partition the retainer's buffer size
// produces. The recording store reports the chunk lengths it actually received, so the
// partitions are shown to have *differed* before their receipts are shown to *agree*; a run
// in which every variant collapsed onto one append would fail rather than pass vacuously.
// The staging side and the claiming side of the handoff are additionally given different
// buffer sizes, so a partition change across the process boundary is exercised too.
//
// ## Why "the digest was recomputed" is observable rather than asserted
//
// The claim's destination store is wrapped, so every chunk it was appended is recorded. The
// arm then requires that the concatenation of those chunks equals the generated array, that
// their total equals the ticketed count, that there was exactly one create and one finalize,
// and that the digest of exactly those recorded bytes equals the digest the resumed session
// carries. A claim path that had copied the ticket's digest instead of measuring one would
// still satisfy "the digests agree" and would fail here. The App Group payload read count is
// checked against a number derived from `TransferManifestCoding.maximumEncodedByteCount`,
// which is the second half of the same observation: the payload was read on this side.
//
// ## What "routing to validation and enabled provenance" is asserted against
//
// `InputValidating.validate(_:contract:budget:)` and `ProvenanceAnalyzing.analyze(_:in:policy:)`
// each take the whole `ImportedEncodedAsset`, and both adapters live outside this test
// target's module closure — the image pipeline and the provenance modules are not reachable
// from the module the Share Extension links, which is the point of the module graph. So what
// is asserted here is the ingest side of Requirements 2.12 and 2.13: both consumers are
// handed one `EncodedAssetHandle`, the session scope owns exactly the one object that handle
// names, each consumer's read returns the generated array, and the read count shows two
// reads of one object rather than two private copies. Whether the provenance lane exists at
// all is Property 19's statement, and this file always routes to it because the property's
// sentence fixes provenance as enabled.
//
// ## What this file deliberately does not assert
//
//   * Mutation. Changing a payload byte, a count, a digest, a status, a schema field, or a
//     build field before claim is Property 6's statement, and nothing below tampers with a
//     published transfer.
//   * Absence of side effects after a decline or a pre-publication cancellation. That is
//     Property 7's.
//   * Item counts, route vocabulary, and whether a session may exist at all. That is
//     Property 4's, and this file holds every count at exactly one so a refusal cannot be
//     mistaken for a preservation failure.
//   * Decoded dimensions or RGB samples agreeing across the two routes (Requirement 2.14).
//     That needs the image pipeline, which this module cannot reach.
//
// ## The protection level is structural here, and it is held fixed
//
// The level every store, object, and policy below uses is entirely synthetic scaffolding,
// like every capacity, deadline, and budget limit in this target: no protection level in a
// test is an approved release value, and a host run is never Requirement 9.6 evidence. The
// real `PlatformDataProtection` still applies it and still verifies it read back, and every
// arm compares the level a receipt reports against the level that was requested.
//
// It is held at ``PreservationShape/protectionLevel`` rather than generated across the three
// levels, for an environment reason rather than a product one. On the development host this
// suite runs on, opening a file for writing inside a directory that carries either the
// complete or the complete-unless-open attribute is refused by the platform with `EPERM`, so
// a store rooted under such a directory reports `.storeUnavailable` for reasons that have
// nothing to do with bytes. Pinning the level to the one the platform actually permits is
// what keeps a failure in this file attributable to preservation.
// `ProtectedEphemeralFileStoreTests` is where all three levels, the fail-closed refusal, and
// the verified read-back are pinned; nothing here weakens any of that.
//
// ## Nothing here is an approved release value
//
// The Share Extension Resource Budget, the Extension Execution Policy, the Data Lifecycle
// Policy, the store capacity, the copy key the manual instruction addresses, the buffer
// sizes, the byte counts, and every identifier are synthetic fixtures that exist so a port
// taking a signed artifact can be called at all. No number below may be copied into a
// shipping artifact.
//
// ## Why no arm throws
//
// `propertyCheck` runs its body under `try?`, so an error escaping the body reports a passing
// run in milliseconds with every arm skipped. Nothing below rethrows: every throwing store,
// retainer, publication, and claim call is wrapped into a value or reported through
// `Issue.record`, and ``PreservationVariationWitness`` counts the cases and every arm
// *outside* the body, where an issue is not suppressed. The arm counters are compared against
// the case count rather than against a floor, and the last thing the body does is record that
// it reached the end, so a case that stopped early is countable rather than invisible.

extension Tag {
    /// Design Property 5.
    ///
    /// Declared in this file rather than in a shared tag namespace: each design property gets
    /// one dedicated file, and a shared namespace would be a merge point between property
    /// files written independently of each other.
    @Tag static var property5HandoffAndBytePreservation: Self
}

@Suite(
    "Property 5: handoff session and encoded-byte preservation",
    .tags(.property5HandoffAndBytePreservation)
)
struct HandoffSessionAndBytePreservationPropertyTests {
    /// Runs at the library default of 100 generated cases, which is the minimum the design
    /// requires; `PropertyToolchainWiringTests` pins that default. Every generator is
    /// composed with `zip`, so the shrinkers compose.
    ///
    /// **Validates: Requirements 2.3, 2.9, 2.10, 2.11, 2.12, 2.13, 11.12**
    @Test("Bytes, count, digest, status, and the pending session survive every partition and both routes")
    func preservationHoldsAcrossPartitionsRoutesAndTheHandoff() async {
        let witness = PreservationVariationWitness()

        await propertyCheck(input: PreservationShape.generator) { shape in
            witness.record(shape)
            let scenario = PreservationScenario(shape: shape, witness: witness)
            defer { scenario.removeTemporaryRoots() }

            await scenario.checkEveryChunkPartitionFinalizesTheSameObject()
            if shape.shareRouteRunsFirst {
                await scenario.checkTheShareHandoffPreservesItsSessionAndItsBytes()
                await scenario.checkEveryPreservationStateCrossesTheHandoffUnchanged()
                await scenario.checkThePhotosRouteRetainsAndRoutesTheExactBytes()
                await scenario.checkEveryPreservationStateIsDerivedAndRouted()
            } else {
                await scenario.checkThePhotosRouteRetainsAndRoutesTheExactBytes()
                await scenario.checkEveryPreservationStateIsDerivedAndRouted()
                await scenario.checkTheShareHandoffPreservesItsSessionAndItsBytes()
                await scenario.checkEveryPreservationStateCrossesTheHandoffUnchanged()
            }

            witness.recordCompletedBody()
        }

        witness.expectVariedBaselines()
    }
}

// MARK: - What a generated case varies

/// One way of partitioning the same byte sequence on the way into storage.
///
/// Three, because they are the three shapes a partition can have that matter: one part, an
/// arbitrary non-uniform partition, and the uniform partition a fixed I/O buffer produces.
/// The finalized bytes, count, and digest are identical for all three, which is what the port
/// contract promises and what this arm measures rather than assumes.
private enum ChunkPartitionVariant: String, Hashable, Sendable, CaseIterable {
    /// The whole sequence in one append.
    case wholeSequence = "whole-sequence"

    /// The generated non-uniform partition: parts of differing lengths, each at least one
    /// byte, summing to the whole sequence.
    case generatedPartition = "generated-partition"

    /// The uniform partition the generated buffer size produces, which is the partition the
    /// real streaming copy uses.
    case uniformChunks = "uniform-chunks"
}

/// One downstream consumer of the retained encoded bytes.
///
/// The two Requirements 2.12 and 2.13 name. Each is handed the whole `ImportedEncodedAsset`,
/// which is the shape both real ports take, and reaches bytes the only way anything can:
/// through the handle's storage key. Neither is the real adapter — those live in modules this
/// one cannot reach — so this models the *handoff to* each consumer, not the consumer.
private enum RetainedByteConsumer: String, Hashable, Sendable, CaseIterable {
    case inputValidator = "input-validator"
    case provenanceAnalyzer = "provenance-analyzer"

    /// The handle this consumer receives.
    ///
    /// Deliberately the asset's own handle rather than a derived value: "the identical
    /// retained encoded-byte sequence" is structural because there is one handle naming one
    /// finalized immutable object, and a consumer that could be handed anything else would be
    /// a consumer that could be handed a second copy.
    func handle(of asset: ImportedEncodedAsset) -> EncodedAssetHandle { asset.handle }
}

// MARK: - Generated shape

/// One generated preservation case, plus the fixtures derived from it.
///
/// Every field is a bounded integer or a flag, and each derived value is read off the shape by
/// modulus, so a family is exercised across all of its members over 100 cases instead of
/// collapsing onto one.
private struct PreservationShape: Sendable, CustomStringConvertible {
    /// Drives the generated byte content, the non-uniform partition, and every synthetic
    /// identifier suffix, so a case's values vary together and a failing case names one seed.
    let seed: Int

    /// Bytes in the generated sequence.
    ///
    /// The range straddles ``TransferManifestCoding/maximumEncodedByteCount`` on purpose: a
    /// staged payload at or below that ceiling is a manifest *candidate* during ready-slot
    /// resolution and is therefore read once more than a payload above it, and the arm
    /// compares the observed payload read count against that derivation. It stays well below
    /// the synthetic budget and store ceilings, because a size large enough to reach a limit
    /// would make the outcome depend on a resource breach instead.
    let byteCount: Int

    let basisIndex: Int
    let formIndex: Int
    let chunkIndex: Int
    let claimChunkIndex: Int
    let partitionIndex: Int
    let hintIndex: Int

    /// Whether the Share arms run before the Photos arms.
    ///
    /// The containers are separate, so exercising both orders is what shows that neither
    /// route's preservation depends on the other having run first.
    let shareRouteRunsFirst: Bool

    // MARK: The generated sequence

    var bytes: [UInt8] { Sample.bytes(count: byteCount, seed: UInt8(truncatingIfNeeded: seed)) }

    /// The digest of the generated sequence, computed in this file rather than read from any
    /// value under test. Every digest assertion compares against this.
    var expectedDigest: DefAIkeDomain.SHA256Digest { StreamingSHA256.digest(of: Data(bytes)) }

    // MARK: Preservation

    /// The basis the direct retention and the direct publication record.
    ///
    /// All four, so all three Byte Preservation Statuses are exercised. The two provider
    /// seams can only establish the two bases that reduce to `unknown` — neither `PhotosUI`
    /// nor a sharing application declares byte originality — so the other two arrive through
    /// the retainer's and the store's documented `basis` parameter, which is the only place
    /// either status can come from.
    var basis: PreservationBasis {
        PreservationBasis.allCases[basisIndex % PreservationBasis.allCases.count]
    }

    var sharedForm: SharedRepresentationForm {
        SharedRepresentationForm.allCases[formIndex % SharedRepresentationForm.allCases.count]
    }

    var photosForm: SuppliedRepresentationForm {
        SuppliedRepresentationForm.allCases[formIndex % SuppliedRepresentationForm.allCases.count]
    }

    /// The data-protection level every store, object, and policy in this file uses.
    ///
    /// Structural scaffolding, not an approved value, and deliberately not generated. See
    /// this file's header for the environment reason it is held fixed, and
    /// `ProtectedEphemeralFileStoreTests` for where all three levels are pinned.
    static let protectionLevel: FileProtectionLevel = .completeUntilFirstUserAuthentication

    var protectionLevel: FileProtectionLevel { Self.protectionLevel }

    // MARK: Partitions

    /// I/O buffer size for the staging-side streaming copy.
    var chunkSizeInBytes: Int { Self.chunkSizes[chunkIndex % Self.chunkSizes.count] }

    /// I/O buffer size for the claiming-side recopy.
    ///
    /// Read from the same table one entry along, so the two sides of one handoff never use
    /// the same partition. A boundary change across the process boundary must not change a
    /// byte, a count, or a digest.
    var claimChunkSizeInBytes: Int {
        Self.chunkSizes[(claimChunkIndex + 1) % Self.chunkSizes.count]
    }

    /// How many parts the generated non-uniform partition aims for.
    var partitionTarget: Int {
        Self.partitionTargets[partitionIndex % Self.partitionTargets.count]
    }

    /// A non-uniform partition of the generated sequence.
    ///
    /// Every part is at least one byte and the parts sum to the whole sequence, so it is a
    /// partition rather than a sample. Cut points come from the seed, so a failing case
    /// replays; duplicate cuts simply yield fewer parts, which is still a valid partition and
    /// keeps the construction terminating.
    var chunkPartition: [Int] {
        guard byteCount > 1, partitionTarget > 1 else { return [byteCount] }
        var state = UInt64(bitPattern: Int64(seed)) &* 2_654_435_761 | 1
        var cuts: Set<Int> = []
        for _ in 0..<min(partitionTarget - 1, byteCount - 1) {
            state = state &* 6_364_136_223_846_793_005 &+ 1_442_695_040_888_963_407
            cuts.insert(1 + Int((state >> 33) % UInt64(byteCount - 1)))
        }
        var parts: [Int] = []
        var previous = 0
        for cut in cuts.sorted() {
            parts.append(cut - previous)
            previous = cut
        }
        parts.append(byteCount - previous)
        return parts
    }

    /// The chunk lengths one variant writes.
    func chunkLengths(for variant: ChunkPartitionVariant) -> [Int] {
        switch variant {
        case .wholeSequence:
            return [byteCount]
        case .generatedPartition:
            return chunkPartition
        case .uniformChunks:
            return Self.uniformLengths(of: byteCount, chunkedBy: chunkSizeInBytes)
        }
    }

    /// The chunks one variant appends.
    func chunks(for variant: ChunkPartitionVariant) -> [[UInt8]] {
        let sequence = bytes
        var chunks: [[UInt8]] = []
        var offset = 0
        for length in chunkLengths(for: variant) {
            chunks.append(Array(sequence[offset..<(offset + length)]))
            offset += length
        }
        return chunks
    }

    /// How many appends the claiming-side recopy performs.
    var expectedClaimAppendCount: Int {
        Self.uniformLengths(of: byteCount, chunkedBy: claimChunkSizeInBytes).count
    }

    /// How many times a claim reads the staged payload object.
    ///
    /// Two when the payload is small enough to be a manifest candidate during ready-slot
    /// resolution — once there, once for the recopy — and one otherwise. Derived from the
    /// manifest ceiling rather than pinned to a constant, so the arm measures the resolution
    /// pass rather than restating a number.
    var expectedPayloadReadCount: Int {
        UInt64(byteCount) <= TransferManifestCoding.maximumEncodedByteCount ? 2 : 1
    }

    // MARK: Derived fixtures

    var contentTypeHint: ContentTypeHint? {
        guard let raw = Self.hints[hintIndex % Self.hints.count] else { return nil }
        return Sample.contentTypeHint(raw)
    }

    /// Exactly one selected item, so a count refusal cannot be mistaken for a preservation
    /// failure. Counts are Property 4's statement.
    var pickerItem: PhotosPickerItemReference {
        Sample.pickerItem(token: 1, contentTypeHint: contentTypeHint)
    }

    /// Exactly one provider offering exactly one item, for the same reason.
    var activation: ShareActivation {
        Sample.activation(
            Sample.sharedProvider(token: 1, itemCount: 1, contentTypeHint: contentTypeHint)
        )
    }

    /// What the Share route's host offers for this case.
    var sharedOffer: FakeSharedItemAccess.Offer {
        .representation(bytes: bytes, form: sharedForm)
    }

    /// What the Photos route's provider offers for this case.
    var photosOffer: FakePhotosAccess.Offer {
        .representation(
            bytes: bytes,
            form: photosForm,
            suppliedContentTypeHint: contentTypeHint
        )
    }

    // MARK: Identifiers

    func partitionSessionID(_ variant: ChunkPartitionVariant) -> AnalysisSessionID {
        Sample.sessionID("session-p5-partition-\(variant.rawValue)")
    }

    var photosAdapterSessionID: AnalysisSessionID { Sample.sessionID("session-p5-photos-adapter") }
    var retainerSessionID: AnalysisSessionID { Sample.sessionID("session-p5-photos-retainer") }
    var shareCandidateSessionID: AnalysisSessionID { Sample.sessionID("session-p5-share-candidate") }
    var storeCandidateSessionID: AnalysisSessionID { Sample.sessionID("session-p5-store-candidate") }

    /// An identifier no arm may ever resume.
    ///
    /// "Claim resumes that same identifier" needs a value the claim could have produced
    /// instead, or the assertion is only that claim produced *something*.
    var decoySessionID: AnalysisSessionID { Sample.sessionID("session-p5-decoy") }

    // MARK: Tables

    /// Structural buffer sizes. Test scaffolding, not approved values.
    static let chunkSizes = [17, 64, 512, 4_096]

    /// Target part counts for the generated non-uniform partition. Structural.
    static let partitionTargets = [2, 3, 5, 9, 17, 65, 257]

    /// Provider-declared type hints, including none. Recorded, never trusted.
    static let hints: [String?] = [nil, "public.jpeg", "public.png", "public.heic", "public.heif"]

    /// Lengths of a uniform partition of `total` bytes into buffers of `chunk` bytes.
    static func uniformLengths(of total: Int, chunkedBy chunk: Int) -> [Int] {
        guard total > 0, chunk > 0 else { return [] }
        var lengths: [Int] = []
        var remaining = total
        while remaining > 0 {
            let take = min(chunk, remaining)
            lengths.append(take)
            remaining -= take
        }
        return lengths
    }

    var description: String {
        """
        seed \(seed), \(byteCount) bytes, basis \(basis.rawValue), \
        status \(basis.mostConservativeStatus.rawValue), \
        shared form \(sharedForm.rawValue), photos form \(photosForm.rawValue), \
        staging chunk \(chunkSizeInBytes), claim chunk \(claimChunkSizeInBytes), \
        partition target \(partitionTarget) (\(chunkPartition.count) parts), \
        hint \(contentTypeHint?.rawValue ?? "none"), share first \(shareRouteRunsFirst)
        """
    }

    // MARK: Generator

    static var generator: Generator<PreservationShape, AnySequence<Any>> {
        zip(
            Gen.int(in: 0...9_999),
            Gen.int(in: 1...6_000),
            index,
            index,
            index,
            index,
            index,
            zip(index, Gen.bool)
        )
        .map { raw in
            PreservationShape(
                seed: raw.0,
                byteCount: raw.1,
                basisIndex: raw.2,
                formIndex: raw.3,
                chunkIndex: raw.4,
                claimChunkIndex: raw.5,
                partitionIndex: raw.6,
                hintIndex: raw.7.0,
                shareRouteRunsFirst: raw.7.1
            )
        }
        .eraseToAny()
    }

    /// A selector index.
    ///
    /// The range is a multiple of every modulus it is reduced by (2, 4, 5, 7), so each table
    /// entry is drawn with equal probability rather than with a modulus bias.
    private static var index: Generator<Int, AnySequence<Any>> {
        Gen.int(in: 0...279).eraseToAny()
    }
}

// MARK: - The reference model

/// What the requirements say about a preservation record, written from the requirement rather
/// than from the code under test.
///
/// Small on purpose. The value of an oracle this shape is that it restates Requirements 2.9
/// through 2.11 — an original-representation declaration is the only evidence that reaches
/// `originalBytes`, a transformed declaration reaches the platform-transformed status, and
/// everything else is `unknown` — so the comparison is against the requirement rather than
/// against a second reading of `PreservationBasis.mostConservativeStatus`.
private enum ReferencePreservationModel {
    static func recordedStatus(for basis: PreservationBasis) -> BytePreservationStatus {
        switch basis {
        case .providerDeclaredOriginalRepresentation:
            .originalBytes
        case .providerDeclaredTransformedRepresentation:
            .platformTransformedCopy
        case .providerDeclaredCurrentRepresentationOnly, .preservationHistoryNotEstablished:
            .unknown
        }
    }
}

// MARK: - A store that records what it was asked to do

/// The real protected store, wrapped so every read and every appended chunk is observable.
///
/// A wrapper rather than a double: the object on disk, its measurements, its protection
/// level, and its atomic rename are all the real ones, and the only thing added is a ledger.
/// That ledger is what turns "the digest was recomputed from the bytes" from a comment into a
/// measurement — the recorded chunks are the bytes that reached storage, so hashing them here
/// and comparing against what the session carries is a check on the production path rather
/// than a restatement of it.
///
/// A locked class rather than an actor, so the ledger can be read synchronously from an arm
/// without another suspension point in the middle of an assertion.
private final class RecordingEphemeralFileStore: EphemeralFileStoring, @unchecked Sendable {
    /// The real store. Held so an arm can reach the members the port does not expose.
    let underlying: ProtectedEphemeralFileStore

    private let lock = NSLock()
    private var readAttempts: [EphemeralStorageKey: Int] = [:]
    private var appendedChunksByKey: [EphemeralStorageKey: [[UInt8]]] = [:]
    private var createdScopes: [EphemeralStorageScope] = []
    private var finalizeAttempts: [EphemeralStorageKey: Int] = [:]

    init(_ underlying: ProtectedEphemeralFileStore) {
        self.underlying = underlying
    }

    // MARK: The ledger

    /// How many times a read of `key` was attempted.
    func readCount(of key: EphemeralStorageKey) -> Int {
        lock.lock()
        defer { lock.unlock() }
        return readAttempts[key] ?? 0
    }

    /// Every chunk appended to `key`, in order.
    func appendedChunks(to key: EphemeralStorageKey) -> [[UInt8]] {
        lock.lock()
        defer { lock.unlock() }
        return appendedChunksByKey[key] ?? []
    }

    /// How many objects were created, across every scope.
    func createCount() -> Int {
        lock.lock()
        defer { lock.unlock() }
        return createdScopes.count
    }

    /// How many times `key` was finalized.
    func finalizeCount(of key: EphemeralStorageKey) -> Int {
        lock.lock()
        defer { lock.unlock() }
        return finalizeAttempts[key] ?? 0
    }

    /// Forgets the ledger without touching a byte on disk.
    ///
    /// Called between a publication and the claim that follows it, so the claim's counts
    /// describe the claim alone.
    func forgetObservations() {
        lock.lock()
        readAttempts = [:]
        appendedChunksByKey = [:]
        createdScopes = []
        finalizeAttempts = [:]
        lock.unlock()
    }

    // MARK: Recording
    //
    // Each recorder is a separate synchronous method: `NSLock` is unavailable from an
    // asynchronous context, and the port members below are `async`.

    private func noteCreate(_ scope: EphemeralStorageScope) {
        lock.lock()
        createdScopes.append(scope)
        lock.unlock()
    }

    private func noteAppend(_ chunk: [UInt8], to key: EphemeralStorageKey) {
        lock.lock()
        appendedChunksByKey[key, default: []].append(chunk)
        lock.unlock()
    }

    private func noteFinalize(_ key: EphemeralStorageKey) {
        lock.lock()
        finalizeAttempts[key, default: 0] += 1
        lock.unlock()
    }

    private func noteRead(_ key: EphemeralStorageKey) {
        lock.lock()
        readAttempts[key, default: 0] += 1
        lock.unlock()
    }

    // MARK: EphemeralFileStoring

    func create(
        in scope: EphemeralStorageScope,
        protection: FileProtectionLevel
    ) async throws(EphemeralStoreError) -> EphemeralStorageKey {
        noteCreate(scope)
        return try await underlying.create(in: scope, protection: protection)
    }

    func append(
        _ chunk: [UInt8],
        to key: EphemeralStorageKey
    ) async throws(EphemeralStoreError) {
        noteAppend(chunk, to: key)
        try await underlying.append(chunk, to: key)
    }

    func finalize(
        _ key: EphemeralStorageKey
    ) async throws(EphemeralStoreError) -> EphemeralWriteReceipt {
        noteFinalize(key)
        return try await underlying.finalize(key)
    }

    func read(_ key: EphemeralStorageKey) async throws(EphemeralStoreError) -> [UInt8] {
        // Counted before the call, so a read that failed is still a read that happened.
        noteRead(key)
        return try await underlying.read(key)
    }

    func receipt(for key: EphemeralStorageKey) async -> EphemeralWriteReceipt? {
        await underlying.receipt(for: key)
    }

    func move(
        _ key: EphemeralStorageKey,
        to scope: EphemeralStorageScope
    ) async throws(EphemeralStoreError) {
        try await underlying.move(key, to: scope)
    }

    func keys(in scope: EphemeralStorageScope) async -> Set<EphemeralStorageKey> {
        await underlying.keys(in: scope)
    }

    func deleteAll(
        in scope: EphemeralStorageScope,
        reason: SessionCleanupReason
    ) async throws(EphemeralStoreError) -> EphemeralDeletionReceipt {
        try await underlying.deleteAll(in: scope, reason: reason)
    }

    func occupiedScopes() async -> Set<EphemeralStorageScope> {
        await underlying.occupiedScopes()
    }
}

// MARK: - One App Group container and the app it hands off to

/// The two roots one handoff spans, and the real surfaces on each side of it.
///
/// Two separate stores, because the whole point of the claim is that the verified bytes end
/// up somewhere the Share Extension cannot reach. Two separate `SharedTransferStore`
/// instances over one shared container, because the extension and the app are two processes:
/// one instance publishes and the other claims, so the ticket really does cross a boundary
/// instead of being handed back through memory.
private struct ShareHandoffContainer {
    let appGroupRoot: URL
    let sessionRoot: URL

    /// The shared container, with a ledger.
    let appGroup: RecordingEphemeralFileStore

    /// App-private session storage, with a ledger. This is where the recopy is measured.
    let session: RecordingEphemeralFileStore

    /// The extension's view of the transfer store.
    let extensionSide: SharedTransferStore

    /// The main app's claim.
    let claimAdapter: ShareHandoffClaimAdapter

    init(appGroupRoot: URL, sessionRoot: URL, shape: PreservationShape) {
        self.appGroupRoot = appGroupRoot
        self.sessionRoot = sessionRoot
        let appGroup = RecordingEphemeralFileStore(
            ProtectedEphemeralFileStore(
                configuration: .test(
                    root: appGroupRoot,
                    containerProtection: shape.protectionLevel
                ),
                protection: PlatformDataProtection(),
                clock: FixedClock(fixtureNow)
            )
        )
        let session = RecordingEphemeralFileStore(
            ProtectedEphemeralFileStore(
                configuration: .test(
                    root: sessionRoot,
                    containerProtection: shape.protectionLevel
                ),
                protection: PlatformDataProtection(),
                clock: FixedClock(fixtureNow)
            )
        )
        self.appGroup = appGroup
        self.session = session
        let policy = Sample.extensionPolicy(stagedFileProtection: shape.protectionLevel)
        self.extensionSide = SharedTransferStore.test(
            over: appGroup,
            extensionPolicy: policy,
            chunkSizeInBytes: shape.chunkSizeInBytes
        )
        self.claimAdapter = ShareHandoffClaimAdapter(
            transfers: SharedTransferStore.test(
                over: appGroup,
                extensionPolicy: policy,
                chunkSizeInBytes: shape.claimChunkSizeInBytes
            ),
            sessionStore: session,
            sessionFileProtection: shape.protectionLevel,
            chunkSizeInBytes: shape.claimChunkSizeInBytes
        )
    }

    /// Every transfer state the shared container still owns that is published.
    func readyTransferScopeCount() async -> Int {
        await appGroup.underlying.occupiedScopes().filter { scope in
            if case .transfer(_, .ready) = scope { return true }
            return false
        }.count
    }
}

// MARK: - The scenario

/// One generated case, run against the real retention, ingest, publication, and claim
/// surfaces.
///
/// Six roots, because each arm has to be able to say "this scope holds exactly one object"
/// without another arm's material satisfying it: the partition arm writes three objects, the
/// two Photos arms write one each under distinct session scopes in one store, and each of the
/// two handoff arms owns its own shared container and its own app-private store so neither
/// competes for the other's single ready slot.
private struct PreservationScenario {
    let shape: PreservationShape
    let witness: PreservationVariationWitness

    private let partitionRoot: URL
    private let partitionStore: RecordingEphemeralFileStore
    private let photosRoot: URL
    private let photosStore: RecordingEphemeralFileStore
    private let coordinatorHandoff: ShareHandoffContainer
    private let storeHandoff: ShareHandoffContainer

    init(shape: PreservationShape, witness: PreservationVariationWitness) {
        self.shape = shape
        self.witness = witness
        self.partitionRoot = Self.temporaryRoot("partition")
        self.partitionStore = RecordingEphemeralFileStore(
            ProtectedEphemeralFileStore(
                configuration: .test(
                    root: partitionRoot,
                    containerProtection: shape.protectionLevel
                ),
                protection: PlatformDataProtection(),
                clock: FixedClock(fixtureNow)
            )
        )
        self.photosRoot = Self.temporaryRoot("photos")
        self.photosStore = RecordingEphemeralFileStore(
            ProtectedEphemeralFileStore(
                configuration: .test(
                    root: photosRoot,
                    containerProtection: shape.protectionLevel
                ),
                protection: PlatformDataProtection(),
                clock: FixedClock(fixtureNow)
            )
        )
        self.coordinatorHandoff = ShareHandoffContainer(
            appGroupRoot: Self.temporaryRoot("coordinator-appgroup"),
            sessionRoot: Self.temporaryRoot("coordinator-session"),
            shape: shape
        )
        self.storeHandoff = ShareHandoffContainer(
            appGroupRoot: Self.temporaryRoot("store-appgroup"),
            sessionRoot: Self.temporaryRoot("store-session"),
            shape: shape
        )
    }

    /// Removes every directory this case owned.
    ///
    /// Synchronous and unconditional so it can run from a `defer` in the property body, and
    /// tolerant of a root that was never created: a case whose store was never written to has
    /// nothing on disk, which is not a failure.
    func removeTemporaryRoots() {
        for root in [
            partitionRoot,
            photosRoot,
            coordinatorHandoff.appGroupRoot,
            coordinatorHandoff.sessionRoot,
            storeHandoff.appGroupRoot,
            storeHandoff.sessionRoot,
        ] {
            try? FileManager.default.removeItem(at: root)
        }
    }

    // MARK: - Any chunk partition

    /// Every partition of the same sequence finalizes one object with the same bytes, the same
    /// count, and the same digest (Requirements 2.9 through 2.11, and the file-store port's
    /// partition contract).
    ///
    /// The partitions are shown to have differed before their receipts are shown to agree: the
    /// recorded chunk lengths are compared against the lengths the shape described, so a run
    /// in which every variant collapsed onto one append fails here instead of passing.
    func checkEveryChunkPartitionFinalizesTheSameObject() async {
        let expectedDigest = shape.expectedDigest
        var receipts: [ChunkPartitionVariant: EphemeralWriteReceipt] = [:]

        for variant in ChunkPartitionVariant.allCases {
            let described = shape.chunkLengths(for: variant)
            // Every part is at least one byte and the parts sum to the sequence, so this is a
            // partition rather than a sample of it.
            #expect(described.allSatisfy { $0 >= 1 }, "\(variant.rawValue) has an empty part")
            #expect(
                described.reduce(0, +) == shape.byteCount,
                "\(variant.rawValue) does not partition \(shape.byteCount) bytes"
            )

            let chunks = shape.chunks(for: variant)
            guard
                let receipt = await write(
                    chunks,
                    in: .session(shape.partitionSessionID(variant))
                )
            else { continue }

            // What the store was actually handed, rather than what it was meant to be handed.
            let recorded = partitionStore.appendedChunks(to: receipt.key)
            #expect(
                recorded.map(\.count) == described,
                "\(variant.rawValue) was written as \(recorded.map(\.count).count) part(s)"
            )
            #expect(
                recorded.flatMap { $0 } == shape.bytes,
                "\(variant.rawValue) was assembled from bytes other than the generated ones"
            )

            #expect(receipt.byteCount == UInt64(shape.byteCount))
            #expect(receipt.sha256 == expectedDigest)
            #expect(receipt.protection == shape.protectionLevel)

            // Byte for byte against the generated array, not digest against digest.
            if let stored = await read(receipt.key, from: partitionStore) {
                #expect(
                    stored == shape.bytes,
                    "\(variant.rawValue) read back \(stored.count) of \(shape.byteCount) bytes"
                )
            }
            receipts[variant] = receipt
            witness.recordPartitionVariant(variant, partCount: described.count)
        }

        guard receipts.count == ChunkPartitionVariant.allCases.count else {
            reportUnbuildableInput("every partition variant must be writable")
            return
        }
        // One count and one digest across every partition. The keys differ, because three
        // objects were written; nothing else does.
        #expect(Set(receipts.values.map(\.byteCount)) == [UInt64(shape.byteCount)])
        #expect(Set(receipts.values.map(\.sha256)) == [expectedDigest])
        #expect(Set(receipts.values.map(\.key)).count == ChunkPartitionVariant.allCases.count)
        witness.recordPartitionCheck()
    }

    // MARK: - The Photos route

    /// The Photos route retains the exact bytes, records exactly that route, and hands one
    /// handle to both consumers (Requirements 2.9 through 2.13).
    ///
    /// Driven through the real `PhotosImportAdapter`, so the streaming copy, the derived
    /// status, and the protected object are the production ones.
    func checkThePhotosRouteRetainsAndRoutesTheExactBytes() async {
        let access = FakePhotosAccess(shape.photosOffer)
        let adapter = PhotosImportAdapter(
            access: access,
            store: photosStore,
            sessionFileProtection: shape.protectionLevel,
            chunkSizeInBytes: shape.chunkSizeInBytes
        )
        let session = shape.photosAdapterSessionID

        switch await adapter.attemptImport(of: shape.pickerItem, into: session) {
        case .success(let asset):
            #expect(asset.route == .photosPicker)
            #expect(asset.route != .shareExtension)
            #expect(asset.sessionID == session)
            #expect(asset.sessionID != shape.decoySessionID)
            // The hint recorded is the one the provider supplied with the bytes.
            #expect(asset.contentTypeHint == shape.contentTypeHint)
            checkPreservation(of: asset, expectedBasis: shape.photosForm.preservationBasis)
            await checkBothConsumersReadTheIdenticalSequence(asset, from: photosStore)
            witness.recordRetainedStatus(asset.preservationStatus, basis: asset.preservationBasis)
        case .failure(let failure):
            reportUnbuildableInput(
                "a complete local representation must be retained: \(failure)"
            )
        }
        witness.recordPhotosRouteCheck()
    }

    /// Every valid preservation state is derived from its basis, never chosen, and the retained
    /// bytes are unaffected by which state it is (Requirements 2.9 through 2.13).
    ///
    /// Driven through the real `EncodedAssetRetainer` — the same one both routes copy through —
    /// because its `basis` parameter is the only place the two statuses a provider seam cannot
    /// establish can come from. There is no status parameter to pass, which is the structural
    /// half of the requirement.
    func checkEveryPreservationStateIsDerivedAndRouted() async {
        guard let source = makeProviderRepresentation() else { return }
        defer { removeProviderFile(source) }

        let retainer = EncodedAssetRetainer(
            store: photosStore,
            chunkSizeInBytes: shape.chunkSizeInBytes
        )
        let session = shape.retainerSessionID
        let asset: ImportedEncodedAsset
        do {
            asset = try await retainer.retainAsset(
                ofFileAt: source,
                route: .photosPicker,
                for: session,
                basis: shape.basis,
                contentTypeHint: shape.contentTypeHint,
                protection: shape.protectionLevel
            )
        } catch {
            reportUnbuildableInput("a nonempty representation must be retainable: \(error)")
            return
        }

        #expect(asset.route == .photosPicker)
        #expect(asset.sessionID == session)
        checkPreservation(of: asset, expectedBasis: shape.basis)

        // No other status is recordable from this basis, so the recorded one was derived
        // rather than selected.
        for other in BytePreservationStatus.allCases
        where other != ReferencePreservationModel.recordedStatus(for: shape.basis) {
            #expect(
                !shape.basis.supports(other),
                "\(shape.basis.rawValue) must not support \(other.rawValue)"
            )
        }

        await checkBothConsumersReadTheIdenticalSequence(asset, from: photosStore)

        // "Byte-for-byte identical copy" is a claim about a copy: the source is opened for
        // reading only and is still exactly what it was.
        #expect(
            representationBytes(at: source) == shape.bytes,
            "the provider's representation must be left exactly as it was"
        )
        witness.recordRetainedStatus(asset.preservationStatus, basis: shape.basis)
        witness.recordPreservationStateCheck()
    }

    // MARK: - The Share handoff

    /// A confirmed handoff publishes once, that commit creates exactly one pending session
    /// under the candidate the extension allocated, and claim resumes exactly that identifier
    /// with exactly those bytes (Requirements 2.3, 2.12, 2.13, and 11.12).
    ///
    /// Driven through the real `ShareExtensionIngestCoordinator`, so the consent step, the
    /// staged protection level, the atomic promotion, and the recovery rules are the
    /// production ones rather than a model of them.
    func checkTheShareHandoffPreservesItsSessionAndItsBytes() async {
        let candidate = shape.shareCandidateSessionID
        guard
            let coordinator = ShareExtensionIngestCoordinator(
                access: FakeSharedItemAccess(shape.sharedOffer),
                consentPresenter: ScriptedConsentPresenter.confirming(),
                transfers: coordinatorHandoff.extensionSide,
                governor: ProgrammedShareResourceGovernor(),
                budget: Sample.shareBudget(),
                instruction: Sample.manualInstruction(),
                candidateSessions: FixedCandidateSessionIdentifierSource(candidate)
            )
        else {
            reportUnbuildableInput("the Share ingest coordinator fixture must be constructible")
            return
        }

        // Nothing is pending before the commit, so the pending session the commit creates is
        // countable rather than inherited.
        guard let before = await readySlot(of: coordinatorHandoff) else { return }
        #expect(before == ReadySlotState.empty)
        #expect(await coordinatorHandoff.readyTransferScopeCount() == 0)

        let outcome = await coordinator.handleActivation(shape.activation)
        guard let ticket = outcome.publishedTicket else {
            reportUnbuildableInput(
                "a consented one-item activation must publish exactly one transfer: \(outcome)"
            )
            return
        }

        // Exactly one pending session, and it is the candidate the extension allocated.
        #expect(ticket.sessionID == candidate)
        #expect(ticket.sessionID != shape.decoySessionID)
        #expect(await coordinatorHandoff.readyTransferScopeCount() == 1)
        if let published = await readySlot(of: coordinatorHandoff)?.publishedTransfer {
            #expect(published.ticket == ticket)
            #expect(published.ticket.sessionID == candidate)
        } else {
            Issue.record("a published handoff must leave exactly one pending transfer")
        }

        // What the extension handed over, measured during the one streaming copy.
        #expect(ticket.route == .shareExtension)
        #expect(ticket.byteCount == UInt64(shape.byteCount))
        #expect(ticket.sha256 == shape.expectedDigest)
        #expect(ticket.contentTypeHint == shape.contentTypeHint)
        #expect(ticket.preservationBasis == shape.sharedForm.preservationBasis)
        #expect(
            ticket.preservationStatus
                == ReferencePreservationModel.recordedStatus(
                    for: shape.sharedForm.preservationBasis
                )
        )
        witness.recordPublishedCommit()

        await claimAndCheck(
            coordinatorHandoff,
            ticket: ticket,
            expectedBasis: shape.sharedForm.preservationBasis,
            candidate: candidate,
            label: "coordinator"
        )
        witness.recordShareHandoffCheck()
    }

    /// Every valid preservation state crosses the App Group boundary unchanged
    /// (Requirements 2.3 and 11.12).
    ///
    /// Published through the real `SharedTransferStore` commit rather than through the
    /// coordinator, because the two statuses a sharing application cannot establish arrive
    /// through the store's documented `basis` parameter — the same call the coordinator makes.
    /// The status is still not a parameter: the store derives it, so a caller cannot publish a
    /// status its basis does not support.
    func checkEveryPreservationStateCrossesTheHandoffUnchanged() async {
        guard let source = makeProviderRepresentation() else { return }
        defer { removeProviderFile(source) }

        let candidate = shape.storeCandidateSessionID
        let ticket: ShareTransferTicket
        do {
            ticket = try await storeHandoff.extensionSide.publishTransfer(
                ofFileAt: source,
                consent: Sample.consent(contentTypeHint: shape.contentTypeHint),
                sessionID: candidate,
                basis: shape.basis
            )
        } catch {
            reportUnbuildableInput("a nonempty representation must be publishable: \(error)")
            return
        }

        #expect(ticket.sessionID == candidate)
        #expect(ticket.sessionID != shape.decoySessionID)
        #expect(ticket.byteCount == UInt64(shape.byteCount))
        #expect(ticket.sha256 == shape.expectedDigest)
        #expect(ticket.preservationBasis == shape.basis)
        #expect(
            ticket.preservationStatus
                == ReferencePreservationModel.recordedStatus(for: shape.basis)
        )
        #expect(await storeHandoff.readyTransferScopeCount() == 1)
        #expect(
            representationBytes(at: source) == shape.bytes,
            "publication must leave the host's representation exactly as it was"
        )

        await claimAndCheck(
            storeHandoff,
            ticket: ticket,
            expectedBasis: shape.basis,
            candidate: candidate,
            label: "store"
        )
        witness.recordStatusCrossedHandoff(ticket.preservationStatus)
        witness.recordPreservationCrossingCheck()
    }

    /// Claims one published transfer and checks everything the claim must preserve.
    ///
    /// The recompute observation lives here. The claim's destination store recorded every
    /// chunk it was appended, so the digest the resumed session carries is compared against
    /// the digest of exactly those recorded bytes: a claim that had copied the ticket's digest
    /// instead of measuring one would satisfy "the digests agree" and fail this.
    private func claimAndCheck(
        _ container: ShareHandoffContainer,
        ticket: ShareTransferTicket,
        expectedBasis: PreservationBasis,
        candidate: AnalysisSessionID,
        label: String
    ) async {
        // Read before the ledgers are cleared: peeking costs reads of the shared container.
        let payloadKey = await readySlot(of: container)?.publishedTransfer?.storageKey
        container.appGroup.forgetObservations()
        container.session.forgetObservations()

        let outcome = await container.claimAdapter.attemptClaim(
            claimingBuildID: Sample.buildID()
        )
        guard let verified = outcome.verifiedHandoff else {
            reportUnbuildableInput("\(label): a published handoff must verify: \(outcome)")
            return
        }
        let asset = verified.asset

        // Claim resumed exactly the pending session the commit created.
        #expect(verified.sessionID == candidate)
        #expect(asset.sessionID == candidate)
        #expect(asset.sessionID != shape.decoySessionID)
        #expect(verified.transferID == ticket.transferID)
        #expect(asset.route == .shareExtension)

        // Every field the ticket published is the field the session carries.
        checkPreservation(of: asset, expectedBasis: expectedBasis)
        #expect(asset.byteCount == ticket.byteCount)
        #expect(asset.sha256 == ticket.sha256)
        #expect(asset.preservationStatus == ticket.preservationStatus)
        #expect(asset.preservationBasis == ticket.preservationBasis)
        #expect(asset.contentTypeHint == ticket.contentTypeHint)

        // The recompute. One object, streamed here, from exactly these bytes.
        let recopied = container.session.appendedChunks(to: asset.handle.storageKey)
        #expect(container.session.createCount() == 1, "\(label): the claim created one object")
        #expect(container.session.finalizeCount(of: asset.handle.storageKey) == 1)
        #expect(
            recopied.count == shape.expectedClaimAppendCount,
            """
            \(label): the recopy streamed \(recopied.count) chunk(s), expected \
            \(shape.expectedClaimAppendCount) at \(shape.claimChunkSizeInBytes) bytes
            """
        )
        #expect(recopied.allSatisfy { $0.count <= shape.claimChunkSizeInBytes })
        let streamed = recopied.flatMap { $0 }
        #expect(
            streamed == shape.bytes,
            "\(label): the recopy streamed \(streamed.count) of \(shape.byteCount) bytes"
        )
        #expect(
            StreamingSHA256.digest(of: Data(streamed)) == asset.sha256,
            """
            \(label): the session's digest must be the digest of the bytes that reached its \
            storage, not the one the ticket carried
            """
        )
        // And the payload really was read on this side. Two reads when the payload is small
        // enough to be a manifest candidate during resolution, one otherwise.
        if let payloadKey {
            #expect(
                container.appGroup.readCount(of: payloadKey)
                    == shape.expectedPayloadReadCount,
                """
                \(label): the staged payload was read \
                \(container.appGroup.readCount(of: payloadKey)) time(s), expected \
                \(shape.expectedPayloadReadCount) for \(shape.byteCount) bytes
                """
            )
        } else {
            Issue.record("\(label): a published transfer must name its payload")
        }

        await checkBothConsumersReadTheIdenticalSequence(asset, from: container.session)

        // Exactly one pending session existed, so a second claim finds nothing rather than
        // the same session again.
        #expect(
            await container.claimAdapter.attemptClaim(claimingBuildID: Sample.buildID())
                == ShareClaimOutcome.nothingPending
        )
        #expect(await readySlot(of: container) == ReadySlotState.empty)
        witness.recordVerifiedClaim()
    }

    // MARK: - Preservation, and routing to both consumers

    /// Every measurement an accepted ingest carries describes the generated sequence, and the
    /// status is the one the basis establishes (Requirements 2.9 through 2.11).
    private func checkPreservation(
        of asset: ImportedEncodedAsset,
        expectedBasis: PreservationBasis
    ) {
        #expect(asset.byteCount == UInt64(shape.byteCount))
        #expect(asset.sha256 == shape.expectedDigest)
        #expect(asset.preservationBasis == expectedBasis)
        #expect(
            asset.preservationStatus
                == ReferencePreservationModel.recordedStatus(for: expectedBasis),
            """
            \(expectedBasis.rawValue) recorded \(asset.preservationStatus.rawValue)
            """
        )
        // The handle is the authoritative measurement; the asset forwards to it, so these
        // cannot be altered independently.
        #expect(asset.handle.byteCount == UInt64(shape.byteCount))
        #expect(asset.handle.sha256 == shape.expectedDigest)
        #expect(asset.handle.protection == shape.protectionLevel)
        #expect(asset.handle.sessionID == asset.sessionID)
    }

    /// Both downstream consumers receive one handle naming one object, and each reads the
    /// generated sequence back element for element (Requirements 2.12 and 2.13).
    private func checkBothConsumersReadTheIdenticalSequence(
        _ asset: ImportedEncodedAsset,
        from store: RecordingEphemeralFileStore
    ) async {
        // Exactly one object is bound to the session, and it is the one the ingest names.
        #expect(
            await store.underlying.keys(in: .session(asset.sessionID))
                == [asset.handle.storageKey],
            "the session must own exactly the object the accepted ingest names"
        )
        // The store's own on-disk measurement, taken during the streaming write.
        if let receipt = await store.receipt(for: asset.handle.storageKey) {
            #expect(receipt.byteCount == UInt64(shape.byteCount))
            #expect(receipt.sha256 == shape.expectedDigest)
            #expect(receipt.protection == shape.protectionLevel)
            #expect(receipt.scope == .session(asset.sessionID))
        } else {
            Issue.record("a retained object must carry the measurements it was written with")
        }

        let readsBefore = store.readCount(of: asset.handle.storageKey)
        var handles: Set<EncodedAssetHandle> = []
        var sequences: [RetainedByteConsumer: [UInt8]] = [:]
        for consumer in RetainedByteConsumer.allCases {
            let handle = consumer.handle(of: asset)
            handles.insert(handle)
            guard let bytes = await read(handle.storageKey, from: store) else { continue }
            sequences[consumer] = bytes
        }

        // One handle, not two: there is no second copy to diverge.
        #expect(handles.count == 1, "the two consumers received \(handles.count) handles")
        #expect(sequences.count == RetainedByteConsumer.allCases.count)
        #expect(
            Set(sequences.values).count == 1,
            "the two consumers read different byte sequences"
        )
        #expect(sequences[.inputValidator] == shape.bytes)
        #expect(sequences[.provenanceAnalyzer] == shape.bytes)
        // Two reads of one object, so neither consumer was served a private copy.
        #expect(
            store.readCount(of: asset.handle.storageKey) - readsBefore
                == RetainedByteConsumer.allCases.count
        )
        witness.recordRoutedToBothConsumers()
    }

    // MARK: - Nonthrowing store calls

    /// Writes `chunks` as one object, or reports why not.
    ///
    /// Wrapped rather than rethrown: an error escaping the property body would report a
    /// passing run with every arm skipped.
    private func write(
        _ chunks: [[UInt8]],
        in scope: EphemeralStorageScope
    ) async -> EphemeralWriteReceipt? {
        do {
            let key = try await partitionStore.create(
                in: scope,
                protection: shape.protectionLevel
            )
            for chunk in chunks {
                try await partitionStore.append(chunk, to: key)
            }
            return try await partitionStore.finalize(key)
        } catch {
            Issue.record("a partitioned object must be writable: \(error)")
            return nil
        }
    }

    private func read(
        _ key: EphemeralStorageKey,
        from store: RecordingEphemeralFileStore
    ) async -> [UInt8]? {
        do {
            return try await store.read(key)
        } catch {
            Issue.record("a finalized object must be readable: \(error)")
            return nil
        }
    }

    private func readySlot(of container: ShareHandoffContainer) async -> ReadySlotState? {
        do {
            return try await container.extensionSide.readySlotState()
        } catch {
            Issue.record("the ready slot must be readable: \(error)")
            return nil
        }
    }

    // MARK: - Helpers

    /// A file standing in for a provider's temporary representation, outside every store root.
    private func makeProviderRepresentation() -> URL? {
        guard let source = try? makeProviderFile(shape.bytes) else {
            reportUnbuildableInput("a provider representation fixture must be writable")
            return nil
        }
        return source
    }

    private func representationBytes(at url: URL) -> [UInt8]? {
        guard let data = try? Data(contentsOf: url) else { return nil }
        return Array(data)
    }

    private func reportUnbuildableInput(
        _ message: Comment,
        sourceLocation: SourceLocation = #_sourceLocation
    ) {
        witness.recordUnbuildableInput()
        Issue.record(message, sourceLocation: sourceLocation)
    }

    private static func temporaryRoot(_ label: String) -> URL {
        URL(fileURLWithPath: NSTemporaryDirectory(), isDirectory: true)
            .appending(
                path: "defaike-p5-\(label)-\(UUID().uuidString)",
                directoryHint: .isDirectory
            )
    }
}

// MARK: - The variation witness

/// Counts what the run generated and what it produced, outside the property body.
///
/// `propertyCheck` runs its body under `try?`, so a body that failed before its first
/// assertion reports a passing test in milliseconds with every arm skipped. Two habits close
/// that gap, and both matter:
///
///   * every arm counter is compared against the **case count** rather than against a floor,
///     so a run in which an arm stopped being reached fails even if the absolute number still
///     looks large; and
///   * ``recordCompletedBody()`` is the last thing the body does, so a case that ended early
///     is countable. `completedBodies == cases` alone would pass vacuously as `0 == 0`, which
///     is why the case floor sits beside it.
///
/// The produced sets are the substantive half. All three Byte Preservation Statuses must have
/// been *recorded* by a retention and must have *crossed* a handoff, all four bases must have
/// been retained, every partition variant must have been written, both read-count branches of
/// the manifest ceiling must have been observed, and a verified claim must have happened twice
/// per case — which is what turns "preservation holds" from a claim about unreached branches
/// into a claim about produced outcomes.
///
/// The variation thresholds are far below what 100 uniform draws produce, so they witness
/// variation rather than pinning a distribution.
private final class PreservationVariationWitness: @unchecked Sendable {
    private let lock = NSLock()

    // Arm counters.
    private var cases = 0
    private var completedBodies = 0
    private var partitionChecks = 0
    private var partitionVariantsWritten = 0
    private var photosRouteChecks = 0
    private var preservationStateChecks = 0
    private var shareHandoffChecks = 0
    private var preservationCrossingChecks = 0
    private var publishedCommits = 0
    private var verifiedClaims = 0
    private var routedToBothConsumers = 0
    private var unbuildableInputs = 0

    // Produced outcomes.
    private var writtenVariants: Set<ChunkPartitionVariant> = []
    private var observedPartCounts: Set<Int> = []
    private var recordedStatuses: Set<BytePreservationStatus> = []
    private var retainedBases: Set<PreservationBasis> = []
    private var statusesAcrossHandoff: Set<BytePreservationStatus> = []

    // Generated baseline.
    private var seeds: Set<Int> = []
    private var byteCounts: Set<Int> = []
    private var bases: Set<PreservationBasis> = []
    private var sharedForms: Set<SharedRepresentationForm> = []
    private var photosForms: Set<SuppliedRepresentationForm> = []
    private var stagingChunkSizes: Set<Int> = []
    private var claimChunkSizes: Set<Int> = []
    private var partitionTargets: Set<Int> = []
    private var hintKeys: Set<String> = []
    private var payloadReadExpectations: Set<Int> = []
    private var routeOrders: Set<Bool> = []

    func record(_ shape: PreservationShape) {
        lock.lock()
        defer { lock.unlock() }
        cases += 1
        seeds.insert(shape.seed)
        byteCounts.insert(shape.byteCount)
        bases.insert(shape.basis)
        sharedForms.insert(shape.sharedForm)
        photosForms.insert(shape.photosForm)
        stagingChunkSizes.insert(shape.chunkSizeInBytes)
        claimChunkSizes.insert(shape.claimChunkSizeInBytes)
        partitionTargets.insert(shape.partitionTarget)
        hintKeys.insert(shape.contentTypeHint?.rawValue ?? "none")
        payloadReadExpectations.insert(shape.expectedPayloadReadCount)
        routeOrders.insert(shape.shareRouteRunsFirst)
    }

    func recordPartitionVariant(_ variant: ChunkPartitionVariant, partCount: Int) {
        lock.lock()
        partitionVariantsWritten += 1
        writtenVariants.insert(variant)
        observedPartCounts.insert(partCount)
        lock.unlock()
    }

    func recordPartitionCheck() {
        lock.lock()
        partitionChecks += 1
        lock.unlock()
    }

    func recordPhotosRouteCheck() {
        lock.lock()
        photosRouteChecks += 1
        lock.unlock()
    }

    func recordPreservationStateCheck() {
        lock.lock()
        preservationStateChecks += 1
        lock.unlock()
    }

    func recordShareHandoffCheck() {
        lock.lock()
        shareHandoffChecks += 1
        lock.unlock()
    }

    func recordPreservationCrossingCheck() {
        lock.lock()
        preservationCrossingChecks += 1
        lock.unlock()
    }

    func recordPublishedCommit() {
        lock.lock()
        publishedCommits += 1
        lock.unlock()
    }

    func recordVerifiedClaim() {
        lock.lock()
        verifiedClaims += 1
        lock.unlock()
    }

    func recordRoutedToBothConsumers() {
        lock.lock()
        routedToBothConsumers += 1
        lock.unlock()
    }

    func recordRetainedStatus(_ status: BytePreservationStatus, basis: PreservationBasis) {
        lock.lock()
        recordedStatuses.insert(status)
        retainedBases.insert(basis)
        lock.unlock()
    }

    func recordStatusCrossedHandoff(_ status: BytePreservationStatus) {
        lock.lock()
        statusesAcrossHandoff.insert(status)
        lock.unlock()
    }

    /// Records that a fixture this file described could not be built.
    ///
    /// Never a finding about preservation: every input here is built from generated integers
    /// inside validated ranges, so a refusal is a defect in this file. It is counted so a run
    /// whose inputs quietly stopped being buildable fails outside the body rather than
    /// shrinking its own coverage.
    func recordUnbuildableInput() {
        lock.lock()
        unbuildableInputs += 1
        lock.unlock()
    }

    /// Called last in the body, so a case that stopped early is countable.
    func recordCompletedBody() {
        lock.lock()
        completedBodies += 1
        lock.unlock()
    }

    func expectVariedBaselines() {
        lock.lock()
        defer { lock.unlock() }

        #expect(cases >= 100, "the design requires at least 100 generated cases; ran \(cases)")
        #expect(
            completedBodies == cases,
            "\(cases - completedBodies) of \(cases) cases did not reach the end of the body"
        )
        #expect(
            unbuildableInputs == 0,
            "\(unbuildableInputs) described inputs could not be built at all"
        )

        // Every arm ran on every case. Compared against the case count rather than against a
        // floor: an arm that stopped being reached fails here even when the absolute number
        // still looks large.
        #expect(partitionChecks == cases, "partition checks: \(partitionChecks)")
        #expect(photosRouteChecks == cases, "Photos route checks: \(photosRouteChecks)")
        #expect(
            preservationStateChecks == cases,
            "preservation state checks: \(preservationStateChecks)"
        )
        #expect(shareHandoffChecks == cases, "Share handoff checks: \(shareHandoffChecks)")
        #expect(
            preservationCrossingChecks == cases,
            "preservation crossing checks: \(preservationCrossingChecks)"
        )
        #expect(publishedCommits == cases, "published commits: \(publishedCommits)")
        // Three partitions per case, two verified claims per case, and four routings: the two
        // Photos arms and the two claims.
        #expect(
            partitionVariantsWritten == cases * ChunkPartitionVariant.allCases.count,
            "partition variants written: \(partitionVariantsWritten)"
        )
        #expect(verifiedClaims == cases * 2, "verified claims: \(verifiedClaims)")
        #expect(
            routedToBothConsumers == cases * 4,
            "assets routed to both consumers: \(routedToBothConsumers)"
        )

        // The substantive half: the outcomes were produced, not merely offered.
        #expect(
            writtenVariants == Set(ChunkPartitionVariant.allCases),
            """
            partition variants never written: \
            \(Set(ChunkPartitionVariant.allCases).subtracting(writtenVariants).map(\.rawValue).sorted())
            """
        )
        #expect(
            observedPartCounts.count >= 6,
            "distinct partition part counts written: \(observedPartCounts.count)"
        )
        #expect(
            recordedStatuses == Set(BytePreservationStatus.allCases),
            """
            statuses never recorded by a retention: \
            \(Set(BytePreservationStatus.allCases).subtracting(recordedStatuses).map(\.rawValue).sorted())
            """
        )
        #expect(
            retainedBases == Set(PreservationBasis.allCases),
            """
            bases never retained: \
            \(Set(PreservationBasis.allCases).subtracting(retainedBases).map(\.rawValue).sorted())
            """
        )
        #expect(
            statusesAcrossHandoff == Set(BytePreservationStatus.allCases),
            """
            statuses that never crossed a handoff: \
            \(Set(BytePreservationStatus.allCases).subtracting(statusesAcrossHandoff).map(\.rawValue).sorted())
            """
        )

        // The generated baseline actually varied.
        #expect(seeds.count >= 50, "generated seeds: \(seeds.count)")
        #expect(byteCounts.count >= 50, "generated byte counts: \(byteCounts.count)")
        #expect(
            bases == Set(PreservationBasis.allCases),
            "generated bases: \(bases.map(\.rawValue).sorted())"
        )
        #expect(
            sharedForms == Set(SharedRepresentationForm.allCases),
            "generated Share representation forms: \(sharedForms.map(\.rawValue).sorted())"
        )
        #expect(
            photosForms == Set(SuppliedRepresentationForm.allCases),
            "generated Photos representation forms: \(photosForms.map(\.rawValue).sorted())"
        )
        #expect(
            stagingChunkSizes == Set(PreservationShape.chunkSizes),
            "generated staging chunk sizes: \(stagingChunkSizes.sorted())"
        )
        #expect(
            claimChunkSizes == Set(PreservationShape.chunkSizes),
            "generated claim chunk sizes: \(claimChunkSizes.sorted())"
        )
        #expect(
            partitionTargets == Set(PreservationShape.partitionTargets),
            "generated partition targets: \(partitionTargets.sorted())"
        )
        #expect(hintKeys.count >= 4, "generated content-type hints: \(hintKeys.sorted())")
        // Both sides of the manifest ceiling: a staged payload that is a resolution candidate
        // and one that is not. The generated byte range straddles the ceiling, so a run that
        // reached only one branch never exercised the read-count derivation.
        #expect(
            payloadReadExpectations == [1, 2],
            "payload read expectations observed: \(payloadReadExpectations.sorted())"
        )
        #expect(routeOrders == [false, true], "only one arm order was generated")
    }
}
